# Caracal — Funding
# ----------------
# Funding here is for Caracal OpenSource only.
#
# It does NOT grant:
# - Any ownership or rights over the code
# - Any governance, roadmap, or decision-making influence
# - Any special commercial or support privileges
#
# Funders may be acknowledged publicly as supporters of Caracal OpenSource.
#
# For any commercial, enterprise, or Caracal OpenSource discussions, please contact:
#   CEO of Garudex Labs — rawx18.dev@gmail.com

github: RAWx18
patreon:
open_collective:
ko_fi: 
tidelift:
community_bridge:
liberapay:
issuehunt:
polar:
buy_me_a_coffee:
thanks_dev: