// SPDX-FileCopyrightText: 2026 RAWx18 <rawx18.dev@gmail.com>
// SPDX-License-Identifier: Apache-2.0

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as OperatorIndexRouteImport } from './routes/operator/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as OrganizationSecurityEventsRouteImport } from './routes/organization/security-events'
import { Route as OrganizationProjectsRouteImport } from './routes/organization/projects'
import { Route as OrganizationMembersRouteImport } from './routes/organization/members'
import { Route as OrganizationAuditLogRouteImport } from './routes/organization/audit-log'
import { Route as OperatorUsersRouteImport } from './routes/operator/users'
import { Route as OperatorTelemetryRouteImport } from './routes/operator/telemetry'
import { Route as OperatorStatusRouteImport } from './routes/operator/status'
import { Route as OperatorSecurityEventsRouteImport } from './routes/operator/security-events'
import { Route as OperatorOrganizationsRouteImport } from './routes/operator/organizations'
import { Route as OperatorAuditLogRouteImport } from './routes/operator/audit-log'
import { Route as OperatorAiEngineRouteImport } from './routes/operator/ai-engine'
import { Route as OperatorAdvancedRouteImport } from './routes/operator/advanced'
import { Route as OnboardingProjectRouteImport } from './routes/onboarding/project'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedIntelligenceRouteImport } from './routes/_authed/intelligence'
import { Route as AuthedUserRouteImport } from './routes/_authed/_user'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authOperatorLoginRouteImport } from './routes/(auth)/operator-login'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authDeviceRouteImport } from './routes/(auth)/device'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedIntelligenceIndexRouteImport } from './routes/_authed/intelligence/index'
import { Route as OnboardingOrganizationNewRouteImport } from './routes/onboarding/organization_.new'
import { Route as AuthedSettingsSsoRouteImport } from './routes/_authed/settings/sso'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings/security'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsPreferencesRouteImport } from './routes/_authed/settings/preferences'
import { Route as AuthedIntelligenceResourcesRouteImport } from './routes/_authed/intelligence/resources'
import { Route as AuthedIntelligenceHistoryRouteImport } from './routes/_authed/intelligence/history'
import { Route as AuthedComponentsComponentIdRouteImport } from './routes/_authed/components/$componentId'
import { Route as AuthedAgentsNewRouteImport } from './routes/_authed/agents/new'
import { Route as AuthedAgentsAgentIdRouteImport } from './routes/_authed/agents/$agentId'
import { Route as AuthedUserInboxRouteImport } from './routes/_authed/_user/inbox'
import { Route as AuthedUserTracesIndexRouteImport } from './routes/_authed/_user/traces/index'
import { Route as AuthedAgentsNamespaceSlugRouteImport } from './routes/_authed/agents/$namespace.$slug'
import { Route as AuthedUserTracesTraceIdRouteImport } from './routes/_authed/_user/traces/$traceId'
import { Route as AuthedAgentsNamespaceSlugIndexRouteImport } from './routes/_authed/agents/$namespace.$slug.index'
import { Route as AuthedComponentsTypeNamespaceSlugRouteImport } from './routes/_authed/components/$type.$namespace.$slug'
import { Route as AuthedAgentsNamespaceSlugEditRouteImport } from './routes/_authed/agents/$namespace.$slug.edit'
import { Route as AuthedAgentsAgentIdInsightsReportIdRouteImport } from './routes/_authed/agents/$agentId/insights/$reportId'

const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const OrganizationSecurityEventsRoute =
  OrganizationSecurityEventsRouteImport.update({
    id: '/security-events',
    path: '/security-events',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationProjectsRoute = OrganizationProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationAuditLogRoute = OrganizationAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => OrganizationRoute,
} as any)
const OperatorUsersRoute = OperatorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorTelemetryRoute = OperatorTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorStatusRoute = OperatorStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSecurityEventsRoute = OperatorSecurityEventsRouteImport.update({
  id: '/security-events',
  path: '/security-events',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOrganizationsRoute = OperatorOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAuditLogRoute = OperatorAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAiEngineRoute = OperatorAiEngineRouteImport.update({
  id: '/ai-engine',
  path: '/ai-engine',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAdvancedRoute = OperatorAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => OperatorRoute,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntelligenceRoute = AuthedIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthedRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authOperatorLoginRoute = authOperatorLoginRouteImport.update({
  id: '/(auth)/operator-login',
  path: '/operator-login',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDeviceRoute = authDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedIntelligenceIndexRoute = AuthedIntelligenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedIntelligenceRoute,
} as any)
const OnboardingOrganizationNewRoute =
  OnboardingOrganizationNewRouteImport.update({
    id: '/organization_/new',
    path: '/organization/new',
    getParentRoute: () => OnboardingRoute,
  } as any)
const AuthedSettingsSsoRoute = AuthedSettingsSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsPreferencesRoute =
  AuthedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedIntelligenceResourcesRoute =
  AuthedIntelligenceResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthedIntelligenceRoute,
  } as any)
const AuthedIntelligenceHistoryRoute =
  AuthedIntelligenceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedIntelligenceRoute,
  } as any)
const AuthedComponentsComponentIdRoute =
  AuthedComponentsComponentIdRouteImport.update({
    id: '/components/$componentId',
    path: '/components/$componentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsNewRoute = AuthedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsAgentIdRoute = AuthedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserInboxRoute = AuthedUserInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedUserRoute,
} as any)
const AuthedUserTracesIndexRoute = AuthedUserTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AuthedUserRoute,
} as any)
const AuthedAgentsNamespaceSlugRoute =
  AuthedAgentsNamespaceSlugRouteImport.update({
    id: '/agents/$namespace/$slug',
    path: '/agents/$namespace/$slug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedUserTracesTraceIdRoute = AuthedUserTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AuthedUserRoute,
} as any)
const AuthedAgentsNamespaceSlugIndexRoute =
  AuthedAgentsNamespaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAgentsNamespaceSlugRoute,
  } as any)
const AuthedComponentsTypeNamespaceSlugRoute =
  AuthedComponentsTypeNamespaceSlugRouteImport.update({
    id: '/components/$type/$namespace/$slug',
    path: '/components/$type/$namespace/$slug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsNamespaceSlugEditRoute =
  AuthedAgentsNamespaceSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedAgentsNamespaceSlugRoute,
  } as any)
const AuthedAgentsAgentIdInsightsReportIdRoute =
  AuthedAgentsAgentIdInsightsReportIdRouteImport.update({
    id: '/insights/$reportId',
    path: '/insights/$reportId',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/operator-login': typeof authOperatorLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/intelligence': typeof AuthedIntelligenceRouteWithChildren
  '/resources': typeof AuthedResourcesRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/operator/advanced': typeof OperatorAdvancedRoute
  '/operator/ai-engine': typeof OperatorAiEngineRoute
  '/operator/audit-log': typeof OperatorAuditLogRoute
  '/operator/organizations': typeof OperatorOrganizationsRoute
  '/operator/security-events': typeof OperatorSecurityEventsRoute
  '/operator/status': typeof OperatorStatusRoute
  '/operator/telemetry': typeof OperatorTelemetryRoute
  '/operator/users': typeof OperatorUsersRoute
  '/organization/audit-log': typeof OrganizationAuditLogRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/projects': typeof OrganizationProjectsRoute
  '/organization/security-events': typeof OrganizationSecurityEventsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/inbox': typeof AuthedUserInboxRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRouteWithChildren
  '/agents/new': typeof AuthedAgentsNewRoute
  '/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/intelligence/history': typeof AuthedIntelligenceHistoryRoute
  '/intelligence/resources': typeof AuthedIntelligenceResourcesRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/sso': typeof AuthedSettingsSsoRoute
  '/onboarding/organization/new': typeof OnboardingOrganizationNewRoute
  '/intelligence/': typeof AuthedIntelligenceIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/agents/$namespace/$slug': typeof AuthedAgentsNamespaceSlugRouteWithChildren
  '/traces/': typeof AuthedUserTracesIndexRoute
  '/agents/$agentId/insights/$reportId': typeof AuthedAgentsAgentIdInsightsReportIdRoute
  '/agents/$namespace/$slug/edit': typeof AuthedAgentsNamespaceSlugEditRoute
  '/components/$type/$namespace/$slug': typeof AuthedComponentsTypeNamespaceSlugRoute
  '/agents/$namespace/$slug/': typeof AuthedAgentsNamespaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/operator-login': typeof authOperatorLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/': typeof AuthedIndexRoute
  '/resources': typeof AuthedResourcesRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/operator/advanced': typeof OperatorAdvancedRoute
  '/operator/ai-engine': typeof OperatorAiEngineRoute
  '/operator/audit-log': typeof OperatorAuditLogRoute
  '/operator/organizations': typeof OperatorOrganizationsRoute
  '/operator/security-events': typeof OperatorSecurityEventsRoute
  '/operator/status': typeof OperatorStatusRoute
  '/operator/telemetry': typeof OperatorTelemetryRoute
  '/operator/users': typeof OperatorUsersRoute
  '/organization/audit-log': typeof OrganizationAuditLogRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/projects': typeof OrganizationProjectsRoute
  '/organization/security-events': typeof OrganizationSecurityEventsRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/inbox': typeof AuthedUserInboxRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRouteWithChildren
  '/agents/new': typeof AuthedAgentsNewRoute
  '/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/intelligence/history': typeof AuthedIntelligenceHistoryRoute
  '/intelligence/resources': typeof AuthedIntelligenceResourcesRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/sso': typeof AuthedSettingsSsoRoute
  '/onboarding/organization/new': typeof OnboardingOrganizationNewRoute
  '/intelligence': typeof AuthedIntelligenceIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/traces': typeof AuthedUserTracesIndexRoute
  '/agents/$agentId/insights/$reportId': typeof AuthedAgentsAgentIdInsightsReportIdRoute
  '/agents/$namespace/$slug/edit': typeof AuthedAgentsNamespaceSlugEditRoute
  '/components/$type/$namespace/$slug': typeof AuthedComponentsTypeNamespaceSlugRoute
  '/agents/$namespace/$slug': typeof AuthedAgentsNamespaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/(auth)/device': typeof authDeviceRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/operator-login': typeof authOperatorLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authed/_user': typeof AuthedUserRouteWithChildren
  '/_authed/intelligence': typeof AuthedIntelligenceRouteWithChildren
  '/_authed/resources': typeof AuthedResourcesRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/operator/advanced': typeof OperatorAdvancedRoute
  '/operator/ai-engine': typeof OperatorAiEngineRoute
  '/operator/audit-log': typeof OperatorAuditLogRoute
  '/operator/organizations': typeof OperatorOrganizationsRoute
  '/operator/security-events': typeof OperatorSecurityEventsRoute
  '/operator/status': typeof OperatorStatusRoute
  '/operator/telemetry': typeof OperatorTelemetryRoute
  '/operator/users': typeof OperatorUsersRoute
  '/organization/audit-log': typeof OrganizationAuditLogRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/projects': typeof OrganizationProjectsRoute
  '/organization/security-events': typeof OrganizationSecurityEventsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/_authed/_user/inbox': typeof AuthedUserInboxRoute
  '/_authed/agents/$agentId': typeof AuthedAgentsAgentIdRouteWithChildren
  '/_authed/agents/new': typeof AuthedAgentsNewRoute
  '/_authed/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/_authed/intelligence/history': typeof AuthedIntelligenceHistoryRoute
  '/_authed/intelligence/resources': typeof AuthedIntelligenceResourcesRoute
  '/_authed/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/_authed/settings/sso': typeof AuthedSettingsSsoRoute
  '/onboarding/organization_/new': typeof OnboardingOrganizationNewRoute
  '/_authed/intelligence/': typeof AuthedIntelligenceIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_user/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/_authed/agents/$namespace/$slug': typeof AuthedAgentsNamespaceSlugRouteWithChildren
  '/_authed/_user/traces/': typeof AuthedUserTracesIndexRoute
  '/_authed/agents/$agentId/insights/$reportId': typeof AuthedAgentsAgentIdInsightsReportIdRoute
  '/_authed/agents/$namespace/$slug/edit': typeof AuthedAgentsNamespaceSlugEditRoute
  '/_authed/components/$type/$namespace/$slug': typeof AuthedComponentsTypeNamespaceSlugRoute
  '/_authed/agents/$namespace/$slug/': typeof AuthedAgentsNamespaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/operator'
    | '/organization'
    | '/device'
    | '/login'
    | '/operator-login'
    | '/register'
    | '/reset-password'
    | '/intelligence'
    | '/resources'
    | '/settings'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/project'
    | '/operator/advanced'
    | '/operator/ai-engine'
    | '/operator/audit-log'
    | '/operator/organizations'
    | '/operator/security-events'
    | '/operator/status'
    | '/operator/telemetry'
    | '/operator/users'
    | '/organization/audit-log'
    | '/organization/members'
    | '/organization/projects'
    | '/organization/security-events'
    | '/onboarding/'
    | '/operator/'
    | '/organization/'
    | '/inbox'
    | '/agents/$agentId'
    | '/agents/new'
    | '/components/$componentId'
    | '/intelligence/history'
    | '/intelligence/resources'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sso'
    | '/onboarding/organization/new'
    | '/intelligence/'
    | '/settings/'
    | '/traces/$traceId'
    | '/agents/$namespace/$slug'
    | '/traces/'
    | '/agents/$agentId/insights/$reportId'
    | '/agents/$namespace/$slug/edit'
    | '/components/$type/$namespace/$slug'
    | '/agents/$namespace/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/device'
    | '/login'
    | '/operator-login'
    | '/register'
    | '/reset-password'
    | '/'
    | '/resources'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/project'
    | '/operator/advanced'
    | '/operator/ai-engine'
    | '/operator/audit-log'
    | '/operator/organizations'
    | '/operator/security-events'
    | '/operator/status'
    | '/operator/telemetry'
    | '/operator/users'
    | '/organization/audit-log'
    | '/organization/members'
    | '/organization/projects'
    | '/organization/security-events'
    | '/onboarding'
    | '/operator'
    | '/organization'
    | '/inbox'
    | '/agents/$agentId'
    | '/agents/new'
    | '/components/$componentId'
    | '/intelligence/history'
    | '/intelligence/resources'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sso'
    | '/onboarding/organization/new'
    | '/intelligence'
    | '/settings'
    | '/traces/$traceId'
    | '/traces'
    | '/agents/$agentId/insights/$reportId'
    | '/agents/$namespace/$slug/edit'
    | '/components/$type/$namespace/$slug'
    | '/agents/$namespace/$slug'
  id:
    | '__root__'
    | '/_authed'
    | '/onboarding'
    | '/operator'
    | '/organization'
    | '/(auth)/device'
    | '/(auth)/login'
    | '/(auth)/operator-login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/_authed/_user'
    | '/_authed/intelligence'
    | '/_authed/resources'
    | '/_authed/settings'
    | '/onboarding/organization'
    | '/onboarding/profile'
    | '/onboarding/project'
    | '/operator/advanced'
    | '/operator/ai-engine'
    | '/operator/audit-log'
    | '/operator/organizations'
    | '/operator/security-events'
    | '/operator/status'
    | '/operator/telemetry'
    | '/operator/users'
    | '/organization/audit-log'
    | '/organization/members'
    | '/organization/projects'
    | '/organization/security-events'
    | '/_authed/'
    | '/onboarding/'
    | '/operator/'
    | '/organization/'
    | '/_authed/_user/inbox'
    | '/_authed/agents/$agentId'
    | '/_authed/agents/new'
    | '/_authed/components/$componentId'
    | '/_authed/intelligence/history'
    | '/_authed/intelligence/resources'
    | '/_authed/settings/preferences'
    | '/_authed/settings/profile'
    | '/_authed/settings/security'
    | '/_authed/settings/sso'
    | '/onboarding/organization_/new'
    | '/_authed/intelligence/'
    | '/_authed/settings/'
    | '/_authed/_user/traces/$traceId'
    | '/_authed/agents/$namespace/$slug'
    | '/_authed/_user/traces/'
    | '/_authed/agents/$agentId/insights/$reportId'
    | '/_authed/agents/$namespace/$slug/edit'
    | '/_authed/components/$type/$namespace/$slug'
    | '/_authed/agents/$namespace/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  OperatorRoute: typeof OperatorRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  authDeviceRoute: typeof authDeviceRoute
  authLoginRoute: typeof authLoginRoute
  authOperatorLoginRoute: typeof authOperatorLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/organization/security-events': {
      id: '/organization/security-events'
      path: '/security-events'
      fullPath: '/organization/security-events'
      preLoaderRoute: typeof OrganizationSecurityEventsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/projects': {
      id: '/organization/projects'
      path: '/projects'
      fullPath: '/organization/projects'
      preLoaderRoute: typeof OrganizationProjectsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/audit-log': {
      id: '/organization/audit-log'
      path: '/audit-log'
      fullPath: '/organization/audit-log'
      preLoaderRoute: typeof OrganizationAuditLogRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/operator/users': {
      id: '/operator/users'
      path: '/users'
      fullPath: '/operator/users'
      preLoaderRoute: typeof OperatorUsersRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/telemetry': {
      id: '/operator/telemetry'
      path: '/telemetry'
      fullPath: '/operator/telemetry'
      preLoaderRoute: typeof OperatorTelemetryRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/status': {
      id: '/operator/status'
      path: '/status'
      fullPath: '/operator/status'
      preLoaderRoute: typeof OperatorStatusRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/security-events': {
      id: '/operator/security-events'
      path: '/security-events'
      fullPath: '/operator/security-events'
      preLoaderRoute: typeof OperatorSecurityEventsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/organizations': {
      id: '/operator/organizations'
      path: '/organizations'
      fullPath: '/operator/organizations'
      preLoaderRoute: typeof OperatorOrganizationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/audit-log': {
      id: '/operator/audit-log'
      path: '/audit-log'
      fullPath: '/operator/audit-log'
      preLoaderRoute: typeof OperatorAuditLogRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/ai-engine': {
      id: '/operator/ai-engine'
      path: '/ai-engine'
      fullPath: '/operator/ai-engine'
      preLoaderRoute: typeof OperatorAiEngineRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/advanced': {
      id: '/operator/advanced'
      path: '/advanced'
      fullPath: '/operator/advanced'
      preLoaderRoute: typeof OperatorAdvancedRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/intelligence': {
      id: '/_authed/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthedIntelligenceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user': {
      id: '/_authed/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/operator-login': {
      id: '/(auth)/operator-login'
      path: '/operator-login'
      fullPath: '/operator-login'
      preLoaderRoute: typeof authOperatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/device': {
      id: '/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof authDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/intelligence/': {
      id: '/_authed/intelligence/'
      path: '/'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof AuthedIntelligenceIndexRouteImport
      parentRoute: typeof AuthedIntelligenceRoute
    }
    '/onboarding/organization_/new': {
      id: '/onboarding/organization_/new'
      path: '/organization/new'
      fullPath: '/onboarding/organization/new'
      preLoaderRoute: typeof OnboardingOrganizationNewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/settings/sso': {
      id: '/_authed/settings/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof AuthedSettingsSsoRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/preferences': {
      id: '/_authed/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthedSettingsPreferencesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/intelligence/resources': {
      id: '/_authed/intelligence/resources'
      path: '/resources'
      fullPath: '/intelligence/resources'
      preLoaderRoute: typeof AuthedIntelligenceResourcesRouteImport
      parentRoute: typeof AuthedIntelligenceRoute
    }
    '/_authed/intelligence/history': {
      id: '/_authed/intelligence/history'
      path: '/history'
      fullPath: '/intelligence/history'
      preLoaderRoute: typeof AuthedIntelligenceHistoryRouteImport
      parentRoute: typeof AuthedIntelligenceRoute
    }
    '/_authed/components/$componentId': {
      id: '/_authed/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof AuthedComponentsComponentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/new': {
      id: '/_authed/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthedAgentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$agentId': {
      id: '/_authed/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user/inbox': {
      id: '/_authed/_user/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedUserInboxRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/_user/traces/': {
      id: '/_authed/_user/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AuthedUserTracesIndexRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/agents/$namespace/$slug': {
      id: '/_authed/agents/$namespace/$slug'
      path: '/agents/$namespace/$slug'
      fullPath: '/agents/$namespace/$slug'
      preLoaderRoute: typeof AuthedAgentsNamespaceSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user/traces/$traceId': {
      id: '/_authed/_user/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AuthedUserTracesTraceIdRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/agents/$namespace/$slug/': {
      id: '/_authed/agents/$namespace/$slug/'
      path: '/'
      fullPath: '/agents/$namespace/$slug/'
      preLoaderRoute: typeof AuthedAgentsNamespaceSlugIndexRouteImport
      parentRoute: typeof AuthedAgentsNamespaceSlugRoute
    }
    '/_authed/components/$type/$namespace/$slug': {
      id: '/_authed/components/$type/$namespace/$slug'
      path: '/components/$type/$namespace/$slug'
      fullPath: '/components/$type/$namespace/$slug'
      preLoaderRoute: typeof AuthedComponentsTypeNamespaceSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$namespace/$slug/edit': {
      id: '/_authed/agents/$namespace/$slug/edit'
      path: '/edit'
      fullPath: '/agents/$namespace/$slug/edit'
      preLoaderRoute: typeof AuthedAgentsNamespaceSlugEditRouteImport
      parentRoute: typeof AuthedAgentsNamespaceSlugRoute
    }
    '/_authed/agents/$agentId/insights/$reportId': {
      id: '/_authed/agents/$agentId/insights/$reportId'
      path: '/insights/$reportId'
      fullPath: '/agents/$agentId/insights/$reportId'
      preLoaderRoute: typeof AuthedAgentsAgentIdInsightsReportIdRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
  }
}

interface AuthedUserRouteChildren {
  AuthedUserInboxRoute: typeof AuthedUserInboxRoute
  AuthedUserTracesTraceIdRoute: typeof AuthedUserTracesTraceIdRoute
  AuthedUserTracesIndexRoute: typeof AuthedUserTracesIndexRoute
}

const AuthedUserRouteChildren: AuthedUserRouteChildren = {
  AuthedUserInboxRoute: AuthedUserInboxRoute,
  AuthedUserTracesTraceIdRoute: AuthedUserTracesTraceIdRoute,
  AuthedUserTracesIndexRoute: AuthedUserTracesIndexRoute,
}

const AuthedUserRouteWithChildren = AuthedUserRoute._addFileChildren(
  AuthedUserRouteChildren,
)

interface AuthedIntelligenceRouteChildren {
  AuthedIntelligenceHistoryRoute: typeof AuthedIntelligenceHistoryRoute
  AuthedIntelligenceResourcesRoute: typeof AuthedIntelligenceResourcesRoute
  AuthedIntelligenceIndexRoute: typeof AuthedIntelligenceIndexRoute
}

const AuthedIntelligenceRouteChildren: AuthedIntelligenceRouteChildren = {
  AuthedIntelligenceHistoryRoute: AuthedIntelligenceHistoryRoute,
  AuthedIntelligenceResourcesRoute: AuthedIntelligenceResourcesRoute,
  AuthedIntelligenceIndexRoute: AuthedIntelligenceIndexRoute,
}

const AuthedIntelligenceRouteWithChildren =
  AuthedIntelligenceRoute._addFileChildren(AuthedIntelligenceRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsPreferencesRoute: typeof AuthedSettingsPreferencesRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsSsoRoute: typeof AuthedSettingsSsoRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsPreferencesRoute: AuthedSettingsPreferencesRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsSsoRoute: AuthedSettingsSsoRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedAgentsAgentIdRouteChildren {
  AuthedAgentsAgentIdInsightsReportIdRoute: typeof AuthedAgentsAgentIdInsightsReportIdRoute
}

const AuthedAgentsAgentIdRouteChildren: AuthedAgentsAgentIdRouteChildren = {
  AuthedAgentsAgentIdInsightsReportIdRoute:
    AuthedAgentsAgentIdInsightsReportIdRoute,
}

const AuthedAgentsAgentIdRouteWithChildren =
  AuthedAgentsAgentIdRoute._addFileChildren(AuthedAgentsAgentIdRouteChildren)

interface AuthedAgentsNamespaceSlugRouteChildren {
  AuthedAgentsNamespaceSlugEditRoute: typeof AuthedAgentsNamespaceSlugEditRoute
  AuthedAgentsNamespaceSlugIndexRoute: typeof AuthedAgentsNamespaceSlugIndexRoute
}

const AuthedAgentsNamespaceSlugRouteChildren: AuthedAgentsNamespaceSlugRouteChildren =
  {
    AuthedAgentsNamespaceSlugEditRoute: AuthedAgentsNamespaceSlugEditRoute,
    AuthedAgentsNamespaceSlugIndexRoute: AuthedAgentsNamespaceSlugIndexRoute,
  }

const AuthedAgentsNamespaceSlugRouteWithChildren =
  AuthedAgentsNamespaceSlugRoute._addFileChildren(
    AuthedAgentsNamespaceSlugRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedUserRoute: typeof AuthedUserRouteWithChildren
  AuthedIntelligenceRoute: typeof AuthedIntelligenceRouteWithChildren
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAgentsAgentIdRoute: typeof AuthedAgentsAgentIdRouteWithChildren
  AuthedAgentsNewRoute: typeof AuthedAgentsNewRoute
  AuthedComponentsComponentIdRoute: typeof AuthedComponentsComponentIdRoute
  AuthedAgentsNamespaceSlugRoute: typeof AuthedAgentsNamespaceSlugRouteWithChildren
  AuthedComponentsTypeNamespaceSlugRoute: typeof AuthedComponentsTypeNamespaceSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUserRoute: AuthedUserRouteWithChildren,
  AuthedIntelligenceRoute: AuthedIntelligenceRouteWithChildren,
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAgentsAgentIdRoute: AuthedAgentsAgentIdRouteWithChildren,
  AuthedAgentsNewRoute: AuthedAgentsNewRoute,
  AuthedComponentsComponentIdRoute: AuthedComponentsComponentIdRoute,
  AuthedAgentsNamespaceSlugRoute: AuthedAgentsNamespaceSlugRouteWithChildren,
  AuthedComponentsTypeNamespaceSlugRoute:
    AuthedComponentsTypeNamespaceSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OnboardingOrganizationNewRoute: typeof OnboardingOrganizationNewRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  OnboardingOrganizationNewRoute: OnboardingOrganizationNewRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface OperatorRouteChildren {
  OperatorAdvancedRoute: typeof OperatorAdvancedRoute
  OperatorAiEngineRoute: typeof OperatorAiEngineRoute
  OperatorAuditLogRoute: typeof OperatorAuditLogRoute
  OperatorOrganizationsRoute: typeof OperatorOrganizationsRoute
  OperatorSecurityEventsRoute: typeof OperatorSecurityEventsRoute
  OperatorStatusRoute: typeof OperatorStatusRoute
  OperatorTelemetryRoute: typeof OperatorTelemetryRoute
  OperatorUsersRoute: typeof OperatorUsersRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAdvancedRoute: OperatorAdvancedRoute,
  OperatorAiEngineRoute: OperatorAiEngineRoute,
  OperatorAuditLogRoute: OperatorAuditLogRoute,
  OperatorOrganizationsRoute: OperatorOrganizationsRoute,
  OperatorSecurityEventsRoute: OperatorSecurityEventsRoute,
  OperatorStatusRoute: OperatorStatusRoute,
  OperatorTelemetryRoute: OperatorTelemetryRoute,
  OperatorUsersRoute: OperatorUsersRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface OrganizationRouteChildren {
  OrganizationAuditLogRoute: typeof OrganizationAuditLogRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationProjectsRoute: typeof OrganizationProjectsRoute
  OrganizationSecurityEventsRoute: typeof OrganizationSecurityEventsRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationAuditLogRoute: OrganizationAuditLogRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationProjectsRoute: OrganizationProjectsRoute,
  OrganizationSecurityEventsRoute: OrganizationSecurityEventsRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  OperatorRoute: OperatorRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  authDeviceRoute: authDeviceRoute,
  authLoginRoute: authLoginRoute,
  authOperatorLoginRoute: authOperatorLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
