"""
Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
Caracal, a product of Garudex Labs

Advanced surface: low-level primitives, codec, bound context plumbing, and the raw coordinator client.
"""

from .envelope import (
    HEADER_AUTHORIZATION,
    HEADER_BAGGAGE,
    HEADER_TRACEPARENT,
    HEADER_TRACESTATE,
    BAGGAGE_AGENT_SESSION,
    BAGGAGE_DELEGATION_EDGE,
    BAGGAGE_HOP,
    BAGGAGE_PARENT_EDGE,
    BAGGAGE_SESSION,
    MAX_HOP,
    Envelope,
    Traceparent,
    decode_envelope,
    encode_envelope,
    encode_baggage,
    format_traceparent,
    from_headers,
    parse_baggage,
    parse_traceparent,
    to_headers,
)
from .context import (
    CaracalContext,
    AuthoritySummary,
    VerifiedClaims,
    abind,
    bind,
    capture_context,
    current,
    describe_authority,
    from_envelope,
    to_envelope,
    with_overrides,
)
from .coordinator import (
    Lifecycle,
    CoordinatorClient,
    DelegationConstraints,
    DelegationRequest,
    DelegationResponse,
    HeartbeatResponse,
    InboundDelegation,
    StartSessionRequest,
    StartSessionResponse,
    create_delegation,
    heartbeat_agent,
    list_inbound_delegations,
    start_coordinator_session,
    terminate_agent,
)
from .primitives import (
    Authority,
    Delegation,
    LifecycleHook,
    SessionHandle,
    attach_session,
    delegate,
    session,
    start_session,
)
from .client import Caracal, CaracalConfig, ResourceBinding
from .errors import CoordinatorError, MissingTokenError
from .http import CaracalASGIMiddleware

__all__ = [
    "HEADER_AUTHORIZATION",
    "HEADER_TRACEPARENT",
    "HEADER_TRACESTATE",
    "HEADER_BAGGAGE",
    "BAGGAGE_AGENT_SESSION",
    "BAGGAGE_DELEGATION_EDGE",
    "BAGGAGE_PARENT_EDGE",
    "BAGGAGE_SESSION",
    "BAGGAGE_HOP",
    "MAX_HOP",
    "Envelope",
    "Traceparent",
    "decode_envelope",
    "encode_envelope",
    "encode_baggage",
    "format_traceparent",
    "from_headers",
    "to_headers",
    "parse_baggage",
    "parse_traceparent",
    "CaracalContext",
    "AuthoritySummary",
    "VerifiedClaims",
    "current",
    "capture_context",
    "bind",
    "abind",
    "describe_authority",
    "with_overrides",
    "to_envelope",
    "from_envelope",
    "Lifecycle",
    "DelegationConstraints",
    "CoordinatorClient",
    "StartSessionRequest",
    "StartSessionResponse",
    "DelegationRequest",
    "DelegationResponse",
    "HeartbeatResponse",
    "InboundDelegation",
    "start_coordinator_session",
    "terminate_agent",
    "heartbeat_agent",
    "create_delegation",
    "list_inbound_delegations",
    "session",
    "start_session",
    "attach_session",
    "Authority",
    "Delegation",
    "SessionHandle",
    "delegate",
    "LifecycleHook",
    "Caracal",
    "CaracalConfig",
    "ResourceBinding",
    "CoordinatorError",
    "MissingTokenError",
    "CaracalASGIMiddleware",
]
