#!/usr/bin/env node
// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Writes apps/cli/src/runtime/version.gen.ts with the runtime CLI identity; CI sets CARACAL_RELEASE_VERSION for GHCR builds, and prerelease builds set CARACAL_PRERELEASE for rc artifacts.

import { execSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const cliRoot = resolve(here, '..')
const repoRoot = resolve(cliRoot, '..', '..')

function shortSha() {
  if (process.env.CARACAL_DEV_SHA) return process.env.CARACAL_DEV_SHA
  try {
    return execSync('git rev-parse --short HEAD', { cwd: repoRoot }).toString().trim()
  } catch {
    return 'nogit'
  }
}

const ciRelease = process.env.CARACAL_RELEASE_VERSION
const sha = shortSha()
const version = ciRelease ?? `dev-${sha}`
const registry = process.env.CARACAL_RELEASE_REGISTRY ?? (ciRelease ? 'ghcr.io/garudex-labs/' : 'localhost/')

if (ciRelease && /\+dev\.|-dev\./.test(ciRelease)) {
  process.stderr.write(`stampRelease: refusing dev-suffixed CARACAL_RELEASE_VERSION '${ciRelease}'\n`)
  process.exit(1)
}
if (ciRelease && /-rc\.sha/.test(ciRelease) && process.env.CARACAL_PRERELEASE !== '1') {
  process.stderr.write(`stampRelease: refusing rc CARACAL_RELEASE_VERSION '${ciRelease}' without CARACAL_PRERELEASE=1\n`)
  process.exit(1)
}

const body =
  `// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped CLI identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_VERSION = '${version}'
export const CARACAL_MODE: 'dev' | 'runtime' = 'runtime'
export const CARACAL_REGISTRY = '${registry}'
export const CARACAL_SHA = '${sha}'
`

const versionFile = resolve(cliRoot, 'src/runtime/version.gen.ts')
mkdirSync(dirname(versionFile), { recursive: true })
writeFileSync(versionFile, body, 'utf8')
process.stdout.write(`stamped runtime version ${version} registry ${registry}\n`)
