#!/usr/bin/env node
// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Writes apps/cli/src/runtime/version.gen.ts with the runtime CLI identity for release CI before bun --compile.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const cliRoot = resolve(here, '..')

function baseVersion() {
  if (process.env.CARACAL_RELEASE_VERSION) return process.env.CARACAL_RELEASE_VERSION
  const raw = readFileSync(resolve(cliRoot, 'runtime/release.json'), 'utf8')
  return JSON.parse(raw).version
}

const version = baseVersion()
if (/\+dev\.|-dev\./.test(version)) {
  process.stderr.write(`stampRelease: refusing dev-suffixed version '${version}'\n`)
  process.exit(1)
}

const body =
  `// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped CLI identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_VERSION = '${version}'
export const CARACAL_MODE: 'dev' | 'runtime' = 'runtime'
`

writeFileSync(resolve(cliRoot, 'src/runtime/version.gen.ts'), body, 'utf8')
process.stdout.write(`stamped runtime version ${version}\n`)
