// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped Terminal identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_TERMINAL_VERSION = '2026.05.14-dev.shaa7825373'
export const CARACAL_TERMINAL_MODE: 'dev' | 'rc' | 'stable' = 'dev'
export const CARACAL_TERMINAL_SHA = 'a7825373'
