// SPDX-FileCopyrightText: 2026 Ryan Madhuwala <rawx18.dev@gmail.com>
// SPDX-License-Identifier: Apache-2.0

// Command checkvulns queries VulnerableCode for known vulnerabilities in
// CycloneDX SBOM components.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const (
	vulnerableCodeAPI = "https://public.vulnerablecode.io/api/packages/bulk_search/"
	batchSize         = 25
	retries           = 3
)

type vulnerability struct {
	VulnerabilityID string `json:"vulnerability_id"`
	Summary         string `json:"summary"`
	URL             string `json:"url"`
}

type packageResult struct {
	Purl                      string          `json:"purl"`
	AffectedByVulnerabilities []vulnerability `json:"affected_by_vulnerabilities"`
}

type finding struct {
	purl            string
	vulnerabilityID string
	summary         string
	url             string
}

// bulkQuery queries the VulnerableCode bulk endpoint for a batch of PURLs.
func bulkQuery(client *http.Client, purls []string) []packageResult {
	payload, err := json.Marshal(map[string][]string{"purls": purls})
	if err != nil {
		fmt.Printf("  Warning: bulk query failed after %d attempts: %v\n", retries, err)
		return nil
	}
	var lastErr error
	for attempt := 0; attempt < retries; attempt++ {
		results, err := postBulk(client, payload)
		if err == nil {
			return results
		}
		lastErr = err
		if attempt < retries-1 {
			time.Sleep(time.Duration(1<<attempt) * time.Second)
		}
	}
	fmt.Printf("  Warning: bulk query failed after %d attempts: %v\n", retries, lastErr)
	return nil
}

func postBulk(client *http.Client, payload []byte) ([]packageResult, error) {
	req, err := http.NewRequest(http.MethodPost, vulnerableCodeAPI, bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("HTTP Error %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
	var results []packageResult
	if err := json.NewDecoder(resp.Body).Decode(&results); err != nil {
		return nil, err
	}
	return results, nil
}

func truncateRunes(s string, n int) string {
	r := []rune(s)
	if len(r) > n {
		return string(r[:n])
	}
	return s
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: checkvulns <sbom1.cdx.json> [sbom2.cdx.json ...]")
		os.Exit(0)
	}

	seen := map[string]bool{}
	for _, sbomPath := range os.Args[1:] {
		raw, err := os.ReadFile(sbomPath)
		if err != nil {
			fmt.Printf("Warning: could not read %s: %v\n", sbomPath, err)
			continue
		}
		var sbom struct {
			Components []struct {
				Purl string `json:"purl"`
			} `json:"components"`
		}
		if err := json.Unmarshal(raw, &sbom); err != nil {
			fmt.Printf("Warning: could not read %s: %v\n", sbomPath, err)
			continue
		}
		for _, comp := range sbom.Components {
			if comp.Purl != "" {
				seen[comp.Purl] = true
			}
		}
	}

	allPurls := make([]string, 0, len(seen))
	for purl := range seen {
		allPurls = append(allPurls, purl)
	}
	sort.Strings(allPurls)
	fmt.Printf("Checking %d packages against VulnerableCode...\n", len(allPurls))

	client := &http.Client{Timeout: 30 * time.Second}
	var findings []finding
	for i := 0; i < len(allPurls); i += batchSize {
		end := i + batchSize
		if end > len(allPurls) {
			end = len(allPurls)
		}
		for _, pkg := range bulkQuery(client, allPurls[i:end]) {
			for _, vuln := range pkg.AffectedByVulnerabilities {
				findings = append(findings, finding{
					purl:            pkg.Purl,
					vulnerabilityID: vuln.VulnerabilityID,
					summary:         truncateRunes(vuln.Summary, 100),
					url:             vuln.URL,
				})
			}
		}
	}

	if len(findings) > 0 {
		var b strings.Builder
		b.WriteString("# SBOM Vulnerability Report\n\n")
		fmt.Fprintf(&b, "Found **%d** known vulnerability(ies) across dependencies.\n\n", len(findings))
		b.WriteString("| Package | Vulnerability | Summary |\n")
		b.WriteString("|---------|--------------|--------|\n")
		for _, item := range findings {
			summary := strings.ReplaceAll(item.summary, "|", "\\|")
			fmt.Fprintf(&b, "| `%s` | [%s](%s) | %s |\n", item.purl, item.vulnerabilityID, item.url, summary)
		}
		b.WriteString(
			"\n---\n*Generated by CI. Non-blocking advisory via " +
				"[VulnerableCode](https://public.vulnerablecode.io)*\n")
		if err := os.WriteFile("vulnerability-report.md", []byte(b.String()), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "error: could not write vulnerability-report.md: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("::warning::Found %d known vulnerabilities. Report saved.\n", len(findings))
	} else {
		fmt.Println("No known vulnerabilities found.")
	}
}
