#!/bin/bash
#
# Setup Redis Security with Authentication and TLS
#
# This script configures Redis with:
# - Password authentication
# - TLS encryption for data in transit
# - Secure configuration settings
#
# Requirements:
# - Redis 6.0+ installed
# - OpenSSL for certificate generation
# - Admin access to Redis server
#

set -e

# Configuration
REDIS_HOME="${REDIS_HOME:-/etc/redis}"
REDIS_CONFIG="${REDIS_CONFIG:-$REDIS_HOME/redis.conf}"
REDIS_CERTS_DIR="${REDIS_CERTS_DIR:-/etc/caracal/redis/certs}"
REDIS_PASSWORD="${REDIS_PASSWORD:-$(openssl rand -base64 32)}"
REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_TLS_PORT="${REDIS_TLS_PORT:-6380}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Redis is installed
if ! command -v redis-server &> /dev/null; then
    log_error "Redis not found. Please install Redis 6.0+"
    log_error "  Ubuntu/Debian: sudo apt-get install redis-server"
    log_error "  CentOS/RHEL: sudo yum install redis"
    log_error "  macOS: brew install redis"
    exit 1
fi

log_info "Setting up Redis security..."
log_info "Redis config: $REDIS_CONFIG"
log_info "Certificates directory: $REDIS_CERTS_DIR"

# Create certificates directory
mkdir -p "$REDIS_CERTS_DIR"
cd "$REDIS_CERTS_DIR"

# Step 1: Generate CA certificate
log_info "Step 1: Generating CA certificate..."
if [ ! -f "ca.key" ]; then
    openssl req -new -x509 -keyout ca.key -out ca.crt -days 365 -nodes \
        -subj "/CN=Caracal-Redis-CA/O=Caracal/C=US"
    log_info "CA certificate generated: ca.crt"
else
    log_warn "CA certificate already exists, skipping generation"
fi

# Step 2: Generate Redis server certificate
log_info "Step 2: Generating Redis server certificate..."
if [ ! -f "redis-server.key" ]; then
    # Generate server private key
    openssl genrsa -out redis-server.key 2048
    
    # Generate certificate signing request
    openssl req -new -key redis-server.key -out redis-server.csr \
        -subj "/CN=redis-server/O=Caracal/C=US"
    
    # Sign certificate with CA
    openssl x509 -req -CA ca.crt -CAkey ca.key -in redis-server.csr \
        -out redis-server.crt -days 365 -CAcreateserial
    
    # Set proper permissions
    chmod 600 redis-server.key
    chmod 644 redis-server.crt
    
    log_info "Redis server certificate generated: redis-server.crt"
else
    log_warn "Redis server certificate already exists, skipping generation"
fi

# Step 3: Generate client certificate for Caracal
log_info "Step 3: Generating client certificate for Caracal..."
if [ ! -f "caracal-client.key" ]; then
    # Generate client private key
    openssl genrsa -out caracal-client.key 2048
    
    # Generate certificate signing request
    openssl req -new -key caracal-client.key -out caracal-client.csr \
        -subj "/CN=caracal-client/O=Caracal/C=US"
    
    # Sign certificate with CA
    openssl x509 -req -CA ca.crt -CAkey ca.key -in caracal-client.csr \
        -out caracal-client.crt -days 365 -CAcreateserial
    
    # Set proper permissions
    chmod 600 caracal-client.key
    chmod 644 caracal-client.crt
    
    log_info "Client certificate generated: caracal-client.crt"
else
    log_warn "Client certificate already exists, skipping generation"
fi

# Step 4: Configure Redis
log_info "Step 4: Configuring Redis..."

# Backup existing redis.conf
if [ -f "$REDIS_CONFIG" ]; then
    cp "$REDIS_CONFIG" "$REDIS_CONFIG.backup"
    log_info "Backed up existing redis.conf"
fi

# Create or update Redis configuration
cat > "$REDIS_CONFIG" <<EOF
# Redis Configuration (generated by setup-redis-security.sh)

# Network
bind 127.0.0.1 ::1
protected-mode yes
port $REDIS_PORT
tcp-backlog 511
timeout 0
tcp-keepalive 300

# TLS Configuration
tls-port $REDIS_TLS_PORT
tls-cert-file $REDIS_CERTS_DIR/redis-server.crt
tls-key-file $REDIS_CERTS_DIR/redis-server.key
tls-ca-cert-file $REDIS_CERTS_DIR/ca.crt
tls-auth-clients no
tls-replication yes
tls-cluster yes

# Authentication
requirepass $REDIS_PASSWORD

# General
daemonize no
supervised no
pidfile /var/run/redis/redis-server.pid
loglevel notice
logfile /var/log/redis/redis-server.log
databases 16

# Snapshotting
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/redis

# Replication
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
replica-priority 100

# Security
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command CONFIG ""
rename-command SHUTDOWN SHUTDOWN_CARACAL

# Limits
maxclients 10000
maxmemory 2gb
maxmemory-policy allkeys-lru

# Append Only File
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes

# Slow Log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Latency Monitor
latency-monitor-threshold 100

# Event Notification
notify-keyspace-events ""

# Advanced Config
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
EOF

log_info "Redis configuration updated: $REDIS_CONFIG"

# Step 5: Create Caracal configuration file
log_info "Step 5: Creating Caracal configuration file..."

cat > "$REDIS_CERTS_DIR/caracal-redis.yaml" <<EOF
redis:
  host: localhost
  port: $REDIS_TLS_PORT
  password: \${REDIS_PASSWORD}  # Set REDIS_PASSWORD environment variable
  db: 0
  ssl: true
  ssl_ca_certs: $REDIS_CERTS_DIR/ca.crt
  ssl_certfile: $REDIS_CERTS_DIR/caracal-client.crt
  ssl_keyfile: $REDIS_CERTS_DIR/caracal-client.key
  spending_cache_ttl: 86400  # 24 hours
  metrics_cache_ttl: 3600  # 1 hour
  allowlist_cache_ttl: 60  # 1 minute
EOF

log_info "Caracal Redis configuration created: $REDIS_CERTS_DIR/caracal-redis.yaml"

# Step 6: Create systemd service file (if systemd is available)
if command -v systemctl &> /dev/null; then
    log_info "Step 6: Creating systemd service file..."
    
    cat > /tmp/redis-caracal.service <<EOF
[Unit]
Description=Redis In-Memory Data Store for Caracal
After=network.target

[Service]
Type=notify
ExecStart=/usr/bin/redis-server $REDIS_CONFIG
ExecStop=/bin/kill -s TERM \$MAINPID
PIDFile=/var/run/redis/redis-server.pid
TimeoutStopSec=0
Restart=always
User=redis
Group=redis
RuntimeDirectory=redis
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
EOF
    
    log_info "Systemd service file created: /tmp/redis-caracal.service"
    log_warn "To install the service, run:"
    log_warn "  sudo mv /tmp/redis-caracal.service /etc/systemd/system/"
    log_warn "  sudo systemctl daemon-reload"
    log_warn "  sudo systemctl enable redis-caracal"
    log_warn "  sudo systemctl start redis-caracal"
fi

# Summary
log_info ""
log_info "========================================="
log_info "Redis Security Setup Complete!"
log_info "========================================="
log_info ""
log_info "Generated files:"
log_info "  - CA certificate: $REDIS_CERTS_DIR/ca.crt"
log_info "  - Server certificate: $REDIS_CERTS_DIR/redis-server.crt"
log_info "  - Server private key: $REDIS_CERTS_DIR/redis-server.key"
log_info "  - Client certificate: $REDIS_CERTS_DIR/caracal-client.crt"
log_info "  - Client private key: $REDIS_CERTS_DIR/caracal-client.key"
log_info "  - Redis config: $REDIS_CONFIG"
log_info "  - Caracal config: $REDIS_CERTS_DIR/caracal-redis.yaml"
log_info ""
log_info "Redis password: $REDIS_PASSWORD"
log_info ""
log_info "Next steps:"
log_info "1. Create required directories:"
log_info "   sudo mkdir -p /var/lib/redis /var/log/redis /var/run/redis"
log_info "   sudo chown redis:redis /var/lib/redis /var/log/redis /var/run/redis"
log_info ""
log_info "2. Start Redis with new configuration:"
log_info "   redis-server $REDIS_CONFIG"
log_info ""
log_info "3. Test connection with authentication:"
log_info "   redis-cli -p $REDIS_TLS_PORT --tls --cacert $REDIS_CERTS_DIR/ca.crt \\"
log_info "     --cert $REDIS_CERTS_DIR/caracal-client.crt \\"
log_info "     --key $REDIS_CERTS_DIR/caracal-client.key \\"
log_info "     -a $REDIS_PASSWORD ping"
log_info ""
log_info "4. Set environment variable for Caracal:"
log_info "   export REDIS_PASSWORD=\"$REDIS_PASSWORD\""
log_info ""
log_info "5. Merge $REDIS_CERTS_DIR/caracal-redis.yaml into your Caracal config"
log_info ""
log_warn "IMPORTANT: Keep the password and private keys secure!"
log_warn "Consider using a secrets management system in production."
log_warn ""
log_warn "Save the Redis password to a secure location:"
echo "$REDIS_PASSWORD" > "$REDIS_CERTS_DIR/redis-password.txt"
chmod 600 "$REDIS_CERTS_DIR/redis-password.txt"
log_info "Password saved to: $REDIS_CERTS_DIR/redis-password.txt"
