# SPDX-FileCopyrightText: 2026 Ryan Madhuwala <rawx18.dev@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: caracal-prometheus
    access: proxy
    url: http://caracal-prometheus:9090
    isDefault: false
    editable: true
