import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  openSourceSidebar: [
    { type: "autogenerated", dirName: "open-source" },
  ],
  enterpriseSidebar: [
    { type: "autogenerated", dirName: "enterprise" },
  ],
  resourcesSidebar: [
    { type: "autogenerated", dirName: "resources" },
  ],
  buildSidebar: [
    { type: "autogenerated", dirName: "build" },
  ],
  manageSidebar: [
    { type: "autogenerated", dirName: "manage" },
  ],
  referenceSidebar: [
    { type: "autogenerated", dirName: "reference" },
  ],
  aiSidebar: [
    { type: "autogenerated", dirName: "ai" },
  ],
};

export default sidebars;
